name: sensory
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - torch
      - scikit-learn
      - dash
      - tqdm
      - "napari[all]"
      - openpyxl
      - seaborn
      - opencv-python
      - numpy
      - matplotlib
      - scikit-image
      - scikit-learn
      - imageio
      - pandas
      - plotly
      - h5py
      - "napari-layer-divider[all]"
      - "napari-label-manager[all]"
  