[workspace]
authors = ["JH Wang <1125623896@qq.com>"]
channels = ["conda-forge"]
name = "sensory_pipeline_python"
platforms = ["win-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
h5py = ">=3.14.0,<4"
pandas = ">=2.3.1,<3"
tifffile = ">=2025.6.11,<2026"
scipy = ">=1.16.1,<2"
matplotlib = ">=3.10.5,<4"
dash = ">=3.2.0,<4"
seaborn = ">=0.13.2,<0.14"
openpyxl = ">=3.1.5,<4"
dask = ">=2025.7.0,<2026"
paramiko = ">=4.0.0,<5"
ipykernel = ">=6.30.1,<7"
opencv = ">=4.12.0,<5"
scikit-learn = ">=1.7.2,<2"
numexpr = ">=2.10.2,<3"
numpy = "2.2.6.*"
napari = ">=0.6.4,<0.7"
freetype = ">=2.14.1,<3"
anywidget = ">=0.9.19,<0.10"
nbformat = ">=5.10.4,<6"
ipywidgets = ">=8.1.8,<9"
pytables = ">=3.10.2,<4"
pytest = ">=9.0.2,<10"
tensorly = ">=0.8.2,<0.9"

[target.osx-arm64.dependencies]
numba = ">=0.61.2,<0.64"
pyqt = ">=5.15,<6"

[pypi-dependencies]
dpca = ">=1.0.5, <2"
napari-label-manager = ">=0.1.4, <0.2"
napari-layer-divider = ">=0.0.3, <0.0.4"
tensorly = "*"

[target.win-64.pypi-dependencies]
numba = "==0.61.2"
